export type OutputFormat = "jpeg" | "png" | "webp" | "avif";
export type FormatPreference = "original" | OutputFormat;
export type CompressionStrategy =
  | "same-format"
  | "png-optimize"
  | "png-quantized"
  | "png-encode-fallback"
  | "webp-lossless"
  | "webp-lossy"
  | "avif-lossy";

export type PngMode = "lossless" | "compressed";

export interface CompressionSettings {
  format: FormatPreference;
  lossless: boolean;
  pngColors: number;
  pngMode: PngMode;
  quality: number;
}

export interface CompressionPreset {
  description: string;
  id: string;
  label: string;
  settings: CompressionSettings;
}

export type CompressionVariantStatus =
  | "processing"
  | "done"
  | "larger-than-original"
  | "error";

export type CompressionJobStatus = "queued" | "processing" | "done" | "error";

export interface CompressionVariant {
  autoGenerated: boolean;
  createdAt: number;
  error?: string;
  format: OutputFormat;
  id: string;
  note?: string;
  output?: Blob;
  outputName?: string;
  presetId: string | null;
  progress: number;
  settings: CompressionSettings;
  signature: string;
  sizeDelta: number | null;
  sourceFormat: OutputFormat | null;
  status: CompressionVariantStatus;
  strategy: CompressionStrategy;
}

export interface CompressionJob {
  activeVariantId: string | null;
  bestVariantId: string | null;
  error?: string;
  file: File;
  id: string;
  status: CompressionJobStatus;
  variants: CompressionVariant[];
}

export interface WorkerCompressRequest {
  autoGenerated: boolean;
  file: File;
  presetId: string | null;
  settings: CompressionSettings;
  sourceFormat: OutputFormat | null;
  sourceId: string;
  strategy: CompressionStrategy;
  variantId: string;
}

export type WorkerProgressStage = "decoding" | "encoding";

export interface WorkerCompressProgress {
  kind: "progress";
  progress: number;
  sourceId: string;
  stage: WorkerProgressStage;
  variantId: string;
}

export interface WorkerCompressSuccess {
  autoGenerated: boolean;
  format: OutputFormat;
  kind: "result";
  note?: string;
  ok: true;
  output: Blob;
  outputName: string;
  sourceFormat: OutputFormat | null;
  sourceId: string;
  strategy: CompressionStrategy;
  variantId: string;
}

export interface WorkerCompressError {
  error: string;
  kind: "result";
  ok: false;
  sourceId: string;
  variantId: string;
}

export interface WorkerRuntimeIssue {
  detail?: string;
  error: string;
  kind: "runtime-error";
  sourceId?: string;
  variantId?: string;
}

export type WorkerCompressResponse =
  | WorkerCompressProgress
  | WorkerCompressSuccess
  | WorkerCompressError
  | WorkerRuntimeIssue;
