/// <reference lib="webworker" />

import { compressImageData, optimiseSourcePng } from "../codecs/compress";
import { buildOutputName } from "../utils/filenames";
import {
  formatFromFile,
  outputExtension,
  resolveOutputFormat,
} from "../utils/format";
import type {
  CompressionStrategy,
  OutputFormat,
  WorkerCompressRequest,
  WorkerCompressResponse,
} from "../utils/types";

function postProgress(
  sourceId: string,
  variantId: string,
  progress: number,
  stage: "decoding" | "encoding"
) {
  const message: WorkerCompressResponse = {
    kind: "progress",
    progress,
    sourceId,
    stage,
    variantId,
  };
  self.postMessage(message);
}

function mimeTypeForFormat(format: OutputFormat) {
  if (format === "png") {
    return "image/png";
  }

  if (format === "webp") {
    return "image/webp";
  }

  if (format === "avif") {
    return "image/avif";
  }

  return "image/jpeg";
}

async function fileToImageData(file: File): Promise<ImageData> {
  const bitmap = await createImageBitmap(file);
  const canvas = new OffscreenCanvas(bitmap.width, bitmap.height);
  const ctx = canvas.getContext("2d");
  if (!ctx) {
    throw new Error("Failed to initialize canvas context in worker.");
  }

  ctx.drawImage(bitmap, 0, 0);
  const imageData = ctx.getImageData(0, 0, bitmap.width, bitmap.height);
  bitmap.close();
  return imageData;
}

async function encodeForStrategy(
  file: File,
  settings: WorkerCompressRequest["settings"],
  strategy: CompressionStrategy
) {
  const sourceFormat = formatFromFile(file);
  const outputFormat = resolveOutputFormat(file, settings.format);

  if (
    sourceFormat === "png" &&
    outputFormat === "png" &&
    (strategy === "oxipng" || strategy === "png-encode")
  ) {
    const sourceBuffer = await file.arrayBuffer();
    const bytesBuffer = await optimiseSourcePng(
      sourceBuffer,
      settings.lossless
    );
    return { bytesBuffer, outputFormat: "png" as const };
  }

  const imageData = await fileToImageData(file);
  const bytesBuffer = await compressImageData(
    imageData,
    {
      ...settings,
      format: outputFormat,
    },
    strategy
  );

  return { bytesBuffer, outputFormat };
}

self.onmessage = async (event: MessageEvent<WorkerCompressRequest>) => {
  const {
    autoGenerated = true,
    sourceId,
    sourceFormat,
    variantId,
    file,
    settings,
    strategy,
  } = event.data as WorkerCompressRequest & { autoGenerated?: boolean };

  try {
    postProgress(sourceId, variantId, 20, "decoding");
    const { bytesBuffer, outputFormat } = await encodeForStrategy(
      file,
      settings,
      strategy
    );
    postProgress(sourceId, variantId, 90, "encoding");
    const requestedExtension = outputExtension(outputFormat);
    const outputName = buildOutputName(file.name, requestedExtension);
    const mime = mimeTypeForFormat(outputFormat);
    const output = new Blob([bytesBuffer], { type: mime });
    const message: WorkerCompressResponse = {
      autoGenerated,
      format: outputFormat,
      kind: "result",
      ok: true,
      output,
      outputName,
      sourceFormat,
      sourceId,
      strategy,
      variantId,
    };
    self.postMessage(message);
  } catch (error) {
    const message: WorkerCompressResponse = {
      error:
        error instanceof Error
          ? error.message
          : "Compression failed unexpectedly.",
      kind: "result",
      ok: false,
      sourceId,
      variantId,
    };
    self.postMessage(message);
  }
};
