import { strToU8, zip } from "fflate";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { sanitizeFilename } from "../../lib/utils/filenames";
import {
  buildSettingsForFormat,
  formatFromFile,
  formatOptions,
  resolveOutputFormat,
  settingsSignature,
} from "../../lib/utils/format";
import { presets } from "../../lib/utils/presets";
import { loadSettings, saveSettings } from "../../lib/utils/storage";
import type {
  CompressionJob,
  CompressionJobStatus,
  CompressionSettings,
  CompressionStrategy,
  CompressionVariant,
  FormatPreference,
  OutputFormat,
  WorkerCompressResponse,
} from "../../lib/utils/types";
import { CompressionList } from "./compression-list";
import { Dropzone } from "./dropzone";
import { ToolbarControls } from "./preset-controls";
import { PreviewPanel } from "./preview-panel";

const defaultSettings: CompressionSettings = {
  format: "original",
  quality: 82,
  lossless: false,
  pngColors: 256,
  pngMode: "lossless",
};

const genericWorkerFailureMessage =
  "The compression worker stopped before it could finish.";

function formatWorkerRuntimeIssue(
  error: string,
  detail?: string,
  context?: string
) {
  const parts = [error.trim()];

  if (context) {
    parts.push(`(${context})`);
  }

  if (detail?.trim()) {
    parts.push(detail.trim());
  }

  return parts.join(" ").trim();
}

function failProcessingJobs(
  current: CompressionJob[],
  error: string
): CompressionJob[] {
  return current.map((job) => ({
    ...job,
    error,
    status: job.status === "processing" ? "error" : job.status,
    variants: job.variants.map((variant) =>
      variant.status === "processing"
        ? {
            ...variant,
            error,
            progress: 100,
            status: "error" as const,
          }
        : variant
    ),
  }));
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

function uniqueName(original: string, used: Set<string>): string {
  const normalizedOriginal = sanitizeFilename(original, "image.jpg");

  if (!used.has(normalizedOriginal)) {
    used.add(normalizedOriginal);
    return normalizedOriginal;
  }

  const dotIndex = normalizedOriginal.lastIndexOf(".");
  const base =
    dotIndex > -1 ? normalizedOriginal.slice(0, dotIndex) : normalizedOriginal;
  const ext = dotIndex > -1 ? normalizedOriginal.slice(dotIndex) : "";

  let count = 1;
  while (used.has(`${base}-${count}${ext}`)) {
    count += 1;
  }

  const next = `${base}-${count}${ext}`;
  used.add(next);
  return next;
}

interface CompressionTask {
  autoGenerated: boolean;
  presetId: string | null;
  settings: CompressionSettings;
  strategy: CompressionStrategy;
}

function formatForStrategy(
  file: File,
  settings: CompressionSettings,
  strategy: CompressionStrategy
): OutputFormat {
  if (
    strategy === "png-optimize" ||
    strategy === "png-quantized" ||
    strategy === "png-encode-fallback"
  ) {
    return "png";
  }

  if (strategy === "webp-lossless" || strategy === "webp-lossy") {
    return "webp";
  }

  if (strategy === "avif-lossy") {
    return "avif";
  }

  return resolveOutputFormat(file, settings.format);
}

function createPendingVariant(
  file: File,
  task: CompressionTask,
  sourceFormat: OutputFormat | null,
  existingId?: string
): CompressionVariant {
  return {
    autoGenerated: task.autoGenerated,
    createdAt: Date.now(),
    format: formatForStrategy(file, task.settings, task.strategy),
    id: existingId ?? crypto.randomUUID(),
    presetId: task.presetId,
    progress: 5,
    settings: task.settings,
    signature: settingsSignature(task.settings, task.presetId, task.strategy),
    sizeDelta: null,
    sourceFormat,
    strategy: task.strategy,
    status: "processing",
  };
}

function buildCompressionTasks(
  file: File,
  settings: CompressionSettings,
  presetId: string | null,
  autoGenerated: boolean
): CompressionTask[] {
  const sourceFormat = formatFromFile(file);

  if (presetId === "keep-quality" && sourceFormat === "png") {
    return [
      {
        autoGenerated,
        presetId,
        settings: {
          format: "original",
          lossless: true,
          pngColors: 256,
          pngMode: "lossless",
          quality: 100,
        },
        strategy: "png-optimize",
      },
    ];
  }

  if (presetId === "smaller-file" && sourceFormat === "png") {
    return [
      {
        autoGenerated,
        presetId,
        settings: {
          format: "webp",
          lossless: false,
          pngColors: 256,
          pngMode: "lossless",
          quality: 82,
        },
        strategy: "webp-lossy",
      },
    ];
  }

  if (presetId === "compressed-png") {
    return [
      {
        autoGenerated,
        presetId,
        settings: {
          ...settings,
          format: "png",
          lossless: true,
          pngColors: settings.pngColors,
          pngMode: "compressed",
        },
        strategy: "png-quantized",
      },
    ];
  }

  if (presetId === "modern-web") {
    return [
      {
        autoGenerated,
        presetId,
        settings: {
          format: "webp",
          lossless: false,
          pngColors: 256,
          pngMode: "lossless",
          quality: 82,
        },
        strategy: "webp-lossy",
      },
    ];
  }

  if (sourceFormat === "png" && settings.format === "original") {
    return [
      {
        autoGenerated,
        presetId,
        settings: { ...settings, lossless: true, pngMode: "lossless" },
        strategy: "png-optimize",
      },
    ];
  }

  if (settings.format === "png") {
    return [
      {
        autoGenerated,
        presetId,
        settings: { ...settings, lossless: true },
        strategy:
          settings.pngMode === "compressed" ? "png-quantized" : "png-optimize",
      },
    ];
  }

  if (settings.format === "webp") {
    return [
      {
        autoGenerated,
        presetId,
        settings,
        strategy: settings.lossless ? "webp-lossless" : "webp-lossy",
      },
    ];
  }

  if (settings.format === "avif") {
    return [
      {
        autoGenerated,
        presetId,
        settings,
        strategy: "avif-lossy",
      },
    ];
  }

  return [
    {
      autoGenerated,
      presetId,
      settings,
      strategy: "same-format",
    },
  ];
}

function getBestVariantId(variants: CompressionVariant[]): string | null {
  const candidates = variants.filter(
    (
      variant
    ): variant is CompressionVariant & { output: Blob; sizeDelta: number } =>
      !!variant.output &&
      variant.sizeDelta !== null &&
      variant.sizeDelta < 0 &&
      variant.status !== "error"
  );

  if (!candidates.length) {
    return null;
  }

  candidates.sort((left, right) => left.output.size - right.output.size);
  return candidates[0]?.id ?? null;
}

function getJobStatus(variants: CompressionVariant[]): CompressionJobStatus {
  if (variants.some((variant) => variant.status === "processing")) {
    return "processing";
  }

  if (
    variants.some(
      (variant) =>
        variant.status === "done" || variant.status === "larger-than-original"
    )
  ) {
    return "done";
  }

  if (variants.some((variant) => variant.status === "error")) {
    return "error";
  }

  return "queued";
}

function updateVariantFromWorker(
  job: CompressionJob,
  variant: CompressionVariant,
  event: WorkerCompressResponse
): CompressionVariant {
  if (event.kind === "runtime-error") {
    if (event.variantId && variant.id !== event.variantId) {
      return variant;
    }

    if (variant.status !== "processing") {
      return variant;
    }

    return {
      ...variant,
      error: formatWorkerRuntimeIssue(event.error, event.detail),
      progress: 100,
      status: "error",
    };
  }

  if (variant.id !== event.variantId) {
    return variant;
  }

  if (event.kind === "progress") {
    return {
      ...variant,
      progress: Math.max(variant.progress, event.progress),
    };
  }

  if (!event.ok) {
    return {
      ...variant,
      error: event.error,
      progress: 100,
      status: "error",
    };
  }

  const sizeDelta = event.output.size - job.file.size;

  return {
    ...variant,
    autoGenerated: event.autoGenerated,
    format: event.format,
    note: event.note,
    output: event.output,
    outputName: event.outputName,
    progress: 100,
    sourceFormat: event.sourceFormat,
    strategy: event.strategy,
    sizeDelta,
    status: sizeDelta > 0 ? "larger-than-original" : "done",
  };
}

function applyWorkerEventToJob(
  job: CompressionJob,
  event: WorkerCompressResponse
): CompressionJob {
  if (event.kind === "runtime-error") {
    if (event.sourceId && job.id !== event.sourceId) {
      return job;
    }

    const error = formatWorkerRuntimeIssue(event.error, event.detail);
    const variants = job.variants.map((variant) =>
      updateVariantFromWorker(job, variant, event)
    );

    return {
      ...job,
      activeVariantId: job.activeVariantId,
      bestVariantId: getBestVariantId(variants),
      error,
      status:
        job.status === "processing" ||
        variants.some((variant) => variant.status === "error")
          ? "error"
          : job.status,
      variants,
    };
  }

  if (job.id !== event.sourceId) {
    return job;
  }

  const variants = job.variants.map((variant) =>
    updateVariantFromWorker(job, variant, event)
  );
  const finishedVariant = variants.find(
    (variant) => variant.id === event.variantId
  );
  const nextBestVariantId = getBestVariantId(variants);
  const activeVariantId =
    finishedVariant?.status === "error"
      ? job.activeVariantId
      : nextBestVariantId;

  return {
    ...job,
    activeVariantId,
    bestVariantId: nextBestVariantId,
    error:
      finishedVariant?.status === "error" ? finishedVariant.error : undefined,
    status: getJobStatus(variants),
    variants,
  };
}

function getVariantById(
  job: CompressionJob | undefined,
  variantId: string | null
) {
  if (!(job && variantId)) {
    return null;
  }

  return job.variants.find((variant) => variant.id === variantId) ?? null;
}

function getDownloadTarget(job: CompressionJob | undefined) {
  if (!job) {
    return null;
  }

  const activeVariant = getVariantById(job, job.activeVariantId);
  if (activeVariant?.output && activeVariant.outputName) {
    return { blob: activeVariant.output, name: activeVariant.outputName };
  }

  const bestVariant = getVariantById(job, job.bestVariantId);
  if (bestVariant?.output && bestVariant.outputName) {
    return { blob: bestVariant.output, name: bestVariant.outputName };
  }

  return { blob: job.file, name: job.file.name };
}

function getLatestJobSettings(
  job: CompressionJob | undefined,
  fallbackSettings: CompressionSettings
) {
  return job?.variants.at(-1)?.settings ?? fallbackSettings;
}

export default function CompressorApp() {
  const [settings, setSettings] = useState<CompressionSettings>(
    () => loadSettings() ?? defaultSettings
  );
  const [activePresetId, setActivePresetId] = useState<string | null>(null);
  const [exportMenuOpen, setExportMenuOpen] = useState(false);
  const [jobs, setJobs] = useState<CompressionJob[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [globalError, setGlobalError] = useState("");
  const addFilesInputRef = useRef<HTMLInputElement>(null);
  const exportMenuRef = useRef<HTMLDivElement>(null);
  const jobsRef = useRef<CompressionJob[]>([]);
  const workerRef = useRef<Worker | null>(null);
  const settingsRef = useRef(settings);

  useEffect(() => {
    settingsRef.current = settings;
  }, [settings]);

  useEffect(() => {
    jobsRef.current = jobs;
  }, [jobs]);

  useEffect(() => {
    function handlePointerDown(event: PointerEvent) {
      if (!exportMenuRef.current?.contains(event.target as Node)) {
        setExportMenuOpen(false);
      }
    }

    if (exportMenuOpen) {
      window.addEventListener("pointerdown", handlePointerDown);
    }

    return () => {
      window.removeEventListener("pointerdown", handlePointerDown);
    };
  }, [exportMenuOpen]);

  const selectedJob = useMemo(
    () => jobs.find((job) => job.id === selectedId),
    [jobs, selectedId]
  );
  const selectedSourceFormat = useMemo(
    () => (selectedJob ? formatFromFile(selectedJob.file) : null),
    [selectedJob]
  );
  const selectedJobSettings = useMemo(
    () => getLatestJobSettings(selectedJob, settings),
    [selectedJob, settings]
  );
  const selectedFormatPreference = selectedJobSettings.format;
  const fallbackSourceFormat = useMemo(
    () => (jobs[0] ? formatFromFile(jobs[0].file) : null),
    [jobs]
  );
  const hasJobs = jobs.length > 0;
  const hasCompleted = jobs.some((job) => job.status === "done");
  const isProcessing = jobs.some((job) => job.status === "processing");

  useEffect(() => {
    return () => {
      workerRef.current?.terminate();
      workerRef.current = null;
    };
  }, []);

  const ensureWorker = useCallback(() => {
    if (!workerRef.current) {
      workerRef.current = new Worker(
        new URL("../../lib/workers/compression.worker.ts", import.meta.url),
        { type: "module" }
      );
      workerRef.current.onmessage = (
        event: MessageEvent<WorkerCompressResponse>
      ) => {
        if (event.data.kind === "runtime-error") {
          const error = formatWorkerRuntimeIssue(
            event.data.error,
            event.data.detail
          );
          console.error("[PixelPress] Worker runtime error", event.data);
          setGlobalError(error);
        }

        setJobs((current) =>
          current.map((job) => applyWorkerEventToJob(job, event.data))
        );
      };
      workerRef.current.onerror = (event) => {
        const error = formatWorkerRuntimeIssue(
          event.message || genericWorkerFailureMessage,
          undefined,
          [
            event.filename ? `file: ${event.filename}` : null,
            event.lineno ? `line: ${event.lineno}` : null,
            event.colno ? `column: ${event.colno}` : null,
          ]
            .filter(Boolean)
            .join(", ") || undefined
        );

        console.error("[PixelPress] Worker onerror", event);
        setGlobalError(error);
        setJobs((current) => failProcessingJobs(current, error));
      };
      workerRef.current.onmessageerror = (event) => {
        const error =
          "The compression worker sent a message the app could not read.";

        console.error("[PixelPress] Worker onmessageerror", event);
        setGlobalError(error);
        setJobs((current) => failProcessingJobs(current, error));
      };
    }
    return workerRef.current;
  }, []);

  function queueCompression(
    sourceId: string,
    nextSettings: CompressionSettings,
    presetId: string | null,
    autoGenerated: boolean
  ) {
    const job = jobsRef.current.find((entry) => entry.id === sourceId);
    if (!job) {
      return;
    }

    const worker = ensureWorker();
    const sourceFormat = formatFromFile(job.file);
    const tasks = buildCompressionTasks(
      job.file,
      nextSettings,
      presetId,
      autoGenerated
    );
    const nextVariants = tasks.map((task) => {
      const existingVariant = job.variants.find(
        (variant) =>
          variant.signature ===
          settingsSignature(task.settings, task.presetId, task.strategy)
      );

      return createPendingVariant(
        job.file,
        task,
        sourceFormat,
        existingVariant?.id
      );
    });

    setJobs((current) =>
      current.map((entry) => {
        if (entry.id !== sourceId) {
          return entry;
        }

        const variants = [
          ...entry.variants.filter(
            (variant) =>
              !nextVariants.some((nextVariant) => nextVariant.id === variant.id)
          ),
          ...nextVariants,
        ].sort((left, right) => left.createdAt - right.createdAt);

        return {
          ...entry,
          activeVariantId: entry.bestVariantId,
          error: undefined,
          status: "processing",
          variants,
        };
      })
    );

    for (const [index, task] of tasks.entries()) {
      const nextVariant = nextVariants[index];
      if (!nextVariant) {
        continue;
      }

      worker.postMessage({
        autoGenerated: task.autoGenerated,
        file: job.file,
        presetId: task.presetId,
        settings: task.settings,
        sourceFormat,
        sourceId,
        strategy: task.strategy,
        variantId: nextVariant.id,
      });
    }
  }

  const addFiles = useCallback(
    (files: File[]) => {
      const selectedFiles = files.filter((file) =>
        file.type.startsWith("image/")
      );

      if (!selectedFiles.length) {
        setGlobalError(
          "Pick image files and PixelPress will take it from there."
        );
        return;
      }

      const currentSettings = settingsRef.current;
      saveSettings(currentSettings);
      setGlobalError("");
      const worker = ensureWorker();

      const nextJobs: CompressionJob[] = selectedFiles.map((file) => {
        const jobId = crypto.randomUUID();
        const sourceFormat = formatFromFile(file);
        const tasks = buildCompressionTasks(file, currentSettings, null, true);
        const variants = tasks.map((task) =>
          createPendingVariant(file, task, sourceFormat)
        );

        for (const [index, task] of tasks.entries()) {
          const variant = variants[index];
          if (!variant) {
            continue;
          }

          worker.postMessage({
            autoGenerated: task.autoGenerated,
            file,
            presetId: task.presetId,
            settings: task.settings,
            sourceFormat,
            sourceId: jobId,
            strategy: task.strategy,
            variantId: variant.id,
          });
        }

        return {
          activeVariantId: null,
          bestVariantId: null,
          file,
          id: jobId,
          status: "processing",
          variants,
        };
      });

      const combined = [...jobsRef.current, ...nextJobs];
      setJobs(combined);
      setSelectedId((existing) => existing ?? combined[0]?.id ?? null);
    },
    [ensureWorker]
  );

  const fileInput = (
    <input
      accept="image/*"
      className="hidden"
      multiple
      onChange={(event) => {
        addFiles(Array.from(event.target.files ?? []));
        event.currentTarget.value = "";
      }}
      ref={addFilesInputRef}
      type="file"
    />
  );

  function handleSettingsChange(nextSettings: CompressionSettings) {
    setActivePresetId(null);
    setSettings(nextSettings);
    saveSettings(nextSettings);
  }

  function handleApplySettings(nextSettings: CompressionSettings) {
    handleSettingsChange(nextSettings);
    if (selectedJob) {
      queueCompression(selectedJob.id, nextSettings, null, false);
    }
  }

  function handleTopFormatChange(format: FormatPreference) {
    if (!selectedJob) {
      return;
    }

    setExportMenuOpen(false);
    const nextSettings = buildSettingsForFormat(selectedJobSettings, format);
    handleSettingsChange(nextSettings);
    queueCompression(selectedJob.id, nextSettings, null, false);
  }

  function handleApplyFormatToAll() {
    if (!jobsRef.current.length) {
      return;
    }

    const nextSettings = buildSettingsForFormat(
      selectedJobSettings,
      selectedFormatPreference
    );

    handleSettingsChange(nextSettings);

    for (const job of jobsRef.current) {
      queueCompression(job.id, nextSettings, null, false);
    }
  }

  function handleApplyPreset(presetId: string) {
    if (!selectedJob) {
      return;
    }

    const presetSettings =
      presets.find((entry) => entry.id === presetId)?.settings ??
      defaultSettings;
    setActivePresetId(presetId);
    setSettings(presetSettings);
    saveSettings(presetSettings);
    queueCompression(selectedJob.id, presetSettings, presetId, true);
  }

  function clearQueue() {
    if (isProcessing) {
      return;
    }
    setJobs([]);
    setSelectedId(null);
    setGlobalError("");
  }

  function openAddFilesPicker() {
    addFilesInputRef.current?.click();
  }

  function downloadSelected() {
    const target = getDownloadTarget(selectedJob);
    if (target) {
      downloadBlob(target.blob, target.name);
    }
  }

  async function downloadAllZip() {
    if (!jobs.length) {
      return;
    }

    try {
      const archive: Record<string, Uint8Array> = {
        "README.txt": strToU8(
          "Generated by PixelPress. Smaller versions are included when they genuinely saved space. Otherwise the original file was kept."
        ),
      };
      const usedNames = new Set<string>(Object.keys(archive));

      for (const job of jobs) {
        const target = getDownloadTarget(job);
        if (!target) {
          continue;
        }

        const safeName = uniqueName(target.name, usedNames);
        archive[safeName] = new Uint8Array(await target.blob.arrayBuffer());
      }

      const zipData = await new Promise<Uint8Array>((resolve, reject) => {
        zip(archive, { level: 6 }, (err, data) => {
          if (err) {
            reject(err);
            return;
          }
          resolve(data);
        });
      });
      const zipBuffer = Uint8Array.from(zipData).buffer;

      downloadBlob(
        new Blob([zipBuffer], { type: "application/zip" }),
        "pixelpress-best-results.zip"
      );
    } catch (err) {
      setGlobalError(
        err instanceof Error ? err.message : "Could not put the zip together."
      );
    }
  }

  function setActiveVariant(sourceId: string, variantId: string | null) {
    setJobs((current) =>
      current.map((job) =>
        job.id === sourceId ? { ...job, activeVariantId: variantId } : job
      )
    );
  }

  if (!hasJobs) {
    return (
      <div className="flex h-[calc(100dvh-3.5rem)] flex-col overflow-hidden">
        <div className="flex flex-1 flex-col">
          <Dropzone onFiles={addFiles} />
        </div>
        {fileInput}
        {globalError && (
          <p className="border-[color:color-mix(in_oklab,var(--color-error)_30%,transparent)] border-t bg-[color:color-mix(in_oklab,var(--color-error)_12%,transparent)] px-4 py-2.5 text-center text-[0.88rem] text-[color:color-mix(in_oklab,var(--color-error)_72%,white_28%)]">
            {globalError}
          </p>
        )}
        <ToolbarControls
          activePresetId={activePresetId}
          hasCompleted={hasCompleted}
          hasJobs={hasJobs}
          hasSelection={!!selectedJob}
          isProcessing={isProcessing}
          onApplyPreset={handleApplyPreset}
          onApplySettings={handleApplySettings}
          onChange={handleSettingsChange}
          onClear={clearQueue}
          onDownloadSelected={downloadSelected}
          onDownloadZip={downloadAllZip}
          settings={selectedJobSettings}
          sourceFormat={selectedSourceFormat ?? fallbackSourceFormat}
        />
      </div>
    );
  }

  return (
    <div className="flex h-[calc(100dvh-3.5rem)] flex-col overflow-hidden">
      <div className="flex flex-wrap items-center justify-between gap-3 border-border border-b px-3 py-2">
        <p className="text-[0.82rem] text-white/55">
          Pick an export format up here. Open Fine tune when you want to adjust
          quality, PNG mode, or lossless details.
        </p>
        <div className="ml-auto flex flex-wrap items-center gap-2">
          <div className="relative" ref={exportMenuRef}>
            <button
              className="inline-flex items-center gap-2 rounded-[0.8rem] border border-border bg-white/[0.03] px-3 py-2 text-[0.82rem] text-muted-strong transition hover:border-border-strong hover:bg-white/[0.05] disabled:cursor-not-allowed disabled:opacity-45"
              disabled={!selectedJob || isProcessing}
              onClick={() => setExportMenuOpen((current) => !current)}
              type="button"
            >
              <span className="text-white/55">Export</span>
              <span className="min-w-[7rem] rounded-[0.6rem] border border-white/10 bg-white/[0.04] px-3 py-1.5 text-left font-medium text-text">
                {formatOptions.find(
                  (format) => format.value === selectedFormatPreference
                )?.label ?? "Original"}
              </span>
              <span
                className={`text-[0.72rem] text-white/45 transition ${exportMenuOpen ? "rotate-180" : ""}`}
              >
                ▾
              </span>
            </button>

            <div
              className={`absolute top-[calc(100%+0.45rem)] right-0 z-20 w-[13rem] origin-top-right rounded-[0.9rem] border border-border bg-[#0d0d0d]/96 p-1.5 shadow-[0_24px_60px_rgba(0,0,0,0.45)] backdrop-blur-xl transition duration-200 ${exportMenuOpen ? "pointer-events-auto translate-y-0 opacity-100" : "pointer-events-none -translate-y-1 opacity-0"}`}
            >
              {formatOptions.map((format) => {
                const active = format.value === selectedFormatPreference;

                return (
                  <button
                    className={`flex w-full items-center justify-between rounded-[0.65rem] px-3 py-2 text-left text-[0.84rem] transition ${
                      active
                        ? "bg-emerald-400/10 text-emerald-200"
                        : "text-text hover:bg-white/6"
                    }`}
                    key={format.value}
                    onClick={() => handleTopFormatChange(format.value)}
                    type="button"
                  >
                    <span className="font-medium">{format.label}</span>
                    {active ? (
                      <span className="text-[0.72rem] text-emerald-300">
                        Active
                      </span>
                    ) : null}
                  </button>
                );
              })}
            </div>
          </div>
          <button
            className="inline-flex items-center gap-1.5 whitespace-nowrap rounded-[0.55rem] border border-border bg-white/4 px-3 py-1.5 font-medium text-[0.82rem] text-muted-strong hover:border-border-strong hover:bg-white/8 disabled:cursor-not-allowed disabled:opacity-45"
            disabled={!hasJobs || isProcessing}
            onClick={handleApplyFormatToAll}
            type="button"
          >
            Apply to all
          </button>
          <button
            className="inline-flex items-center gap-1.5 whitespace-nowrap rounded-[0.55rem] border border-border bg-white/4 px-3 py-1.5 font-medium text-[0.82rem] text-muted-strong hover:border-border-strong hover:bg-white/8"
            onClick={openAddFilesPicker}
            type="button"
          >
            <span className="text-[0.92rem] leading-none">+</span>
            Add files
          </button>
        </div>
        {fileInput}
      </div>

      <div className="flex min-h-0 flex-1 flex-col overflow-hidden md:flex-row">
        <CompressionList
          jobs={jobs}
          onSelect={setSelectedId}
          selectedId={selectedId}
        />
        <div className="flex min-w-0 flex-1 flex-col overflow-hidden">
          <PreviewPanel
            job={selectedJob}
            onSelectVariant={(variantId) => {
              if (selectedJob) {
                setActiveVariant(selectedJob.id, variantId);
              }
            }}
          />
        </div>
      </div>

      {globalError && (
        <p className="border-[color:color-mix(in_oklab,var(--color-error)_30%,transparent)] border-t bg-[color:color-mix(in_oklab,var(--color-error)_12%,transparent)] px-4 py-2.5 text-center text-[0.88rem] text-[color:color-mix(in_oklab,var(--color-error)_72%,white_28%)]">
          {globalError}
        </p>
      )}

      <ToolbarControls
        activePresetId={activePresetId}
        hasCompleted={hasCompleted}
        hasJobs={hasJobs}
        hasSelection={!!selectedJob}
        isProcessing={isProcessing}
        onApplyPreset={handleApplyPreset}
        onApplySettings={handleApplySettings}
        onChange={handleSettingsChange}
        onClear={clearQueue}
        onDownloadSelected={downloadSelected}
        onDownloadZip={downloadAllZip}
        settings={selectedJobSettings}
        sourceFormat={selectedSourceFormat ?? fallbackSourceFormat}
      />
    </div>
  );
}
