import { strToU8, zip } from "fflate";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { sanitizeFilename } from "../../lib/utils/filenames";
import {
  formatFromFile,
  resolveOutputFormat,
  settingsSignature,
} from "../../lib/utils/format";
import { presets } from "../../lib/utils/presets";
import { loadSettings, saveSettings } from "../../lib/utils/storage";
import type {
  CompressionJob,
  CompressionJobStatus,
  CompressionSettings,
  CompressionStrategy,
  CompressionVariant,
  OutputFormat,
  WorkerCompressResponse,
} from "../../lib/utils/types";
import { CompressionList } from "./compression-list";
import { Dropzone } from "./dropzone";
import { ToolbarControls } from "./preset-controls";
import { PreviewPanel } from "./preview-panel";

const defaultSettings: CompressionSettings = {
  format: "original",
  quality: 82,
  lossless: false,
};

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

function uniqueName(original: string, used: Set<string>): string {
  const normalizedOriginal = sanitizeFilename(original, "image.jpg");

  if (!used.has(normalizedOriginal)) {
    used.add(normalizedOriginal);
    return normalizedOriginal;
  }

  const dotIndex = normalizedOriginal.lastIndexOf(".");
  const base =
    dotIndex > -1 ? normalizedOriginal.slice(0, dotIndex) : normalizedOriginal;
  const ext = dotIndex > -1 ? normalizedOriginal.slice(dotIndex) : "";

  let count = 1;
  while (used.has(`${base}-${count}${ext}`)) {
    count += 1;
  }

  const next = `${base}-${count}${ext}`;
  used.add(next);
  return next;
}

interface CompressionTask {
  autoGenerated: boolean;
  presetId: string | null;
  settings: CompressionSettings;
  strategy: CompressionStrategy;
}

function formatForStrategy(
  file: File,
  settings: CompressionSettings,
  strategy: CompressionStrategy
): OutputFormat {
  if (strategy === "oxipng" || strategy === "png-encode") {
    return "png";
  }

  if (strategy === "webp-lossless" || strategy === "webp-lossy") {
    return "webp";
  }

  if (strategy === "avif-lossy") {
    return "avif";
  }

  return resolveOutputFormat(file, settings.format);
}

function createPendingVariant(
  file: File,
  task: CompressionTask,
  sourceFormat: OutputFormat | null,
  existingId?: string
): CompressionVariant {
  return {
    autoGenerated: task.autoGenerated,
    createdAt: Date.now(),
    format: formatForStrategy(file, task.settings, task.strategy),
    id: existingId ?? crypto.randomUUID(),
    presetId: task.presetId,
    progress: 5,
    settings: task.settings,
    signature: settingsSignature(task.settings, task.presetId, task.strategy),
    sizeDelta: null,
    sourceFormat,
    strategy: task.strategy,
    status: "processing",
  };
}

function buildCompressionTasks(
  file: File,
  settings: CompressionSettings,
  presetId: string | null,
  autoGenerated: boolean
): CompressionTask[] {
  const sourceFormat = formatFromFile(file);

  if (presetId === "keep-quality" && sourceFormat === "png") {
    return [
      {
        autoGenerated,
        presetId,
        settings: { format: "png", lossless: true, quality: 100 },
        strategy: "oxipng",
      },
      {
        autoGenerated,
        presetId,
        settings: { format: "webp", lossless: true, quality: 100 },
        strategy: "webp-lossless",
      },
    ];
  }

  if (presetId === "smaller-file" && sourceFormat === "png") {
    return [
      {
        autoGenerated,
        presetId,
        settings: { format: "png", lossless: false, quality: 100 },
        strategy: "oxipng",
      },
      {
        autoGenerated,
        presetId,
        settings: { format: "webp", lossless: false, quality: 82 },
        strategy: "webp-lossy",
      },
    ];
  }

  if (presetId === "modern-web") {
    return [
      {
        autoGenerated,
        presetId,
        settings: { format: "webp", lossless: false, quality: 82 },
        strategy: "webp-lossy",
      },
    ];
  }

  if (sourceFormat === "png" && settings.format === "original") {
    if (autoGenerated) {
      return [
        {
          autoGenerated,
          presetId,
          settings: {
            ...settings,
            format: "png",
            lossless: true,
            quality: 100,
          },
          strategy: "oxipng",
        },
        {
          autoGenerated,
          presetId,
          settings: {
            format: "webp",
            lossless: false,
            quality: settings.quality,
          },
          strategy: "webp-lossy",
        },
      ];
    }

    return [
      {
        autoGenerated,
        presetId,
        settings: { ...settings, format: "png" },
        strategy: "oxipng",
      },
    ];
  }

  if (settings.format === "png") {
    return [
      {
        autoGenerated,
        presetId,
        settings,
        strategy: sourceFormat === "png" ? "oxipng" : "png-encode",
      },
    ];
  }

  if (settings.format === "webp") {
    return [
      {
        autoGenerated,
        presetId,
        settings,
        strategy: settings.lossless ? "webp-lossless" : "webp-lossy",
      },
    ];
  }

  if (settings.format === "avif") {
    return [
      {
        autoGenerated,
        presetId,
        settings,
        strategy: "avif-lossy",
      },
    ];
  }

  return [
    {
      autoGenerated,
      presetId,
      settings,
      strategy: "same-format",
    },
  ];
}

function getBestVariantId(variants: CompressionVariant[]): string | null {
  const candidates = variants.filter(
    (
      variant
    ): variant is CompressionVariant & { output: Blob; sizeDelta: number } =>
      !!variant.output &&
      variant.sizeDelta !== null &&
      variant.sizeDelta < 0 &&
      variant.status !== "error"
  );

  if (!candidates.length) {
    return null;
  }

  candidates.sort((left, right) => left.output.size - right.output.size);
  return candidates[0]?.id ?? null;
}

function getJobStatus(variants: CompressionVariant[]): CompressionJobStatus {
  if (variants.some((variant) => variant.status === "processing")) {
    return "processing";
  }

  if (
    variants.some(
      (variant) =>
        variant.status === "done" || variant.status === "larger-than-original"
    )
  ) {
    return "done";
  }

  if (variants.some((variant) => variant.status === "error")) {
    return "error";
  }

  return "queued";
}

function updateVariantFromWorker(
  job: CompressionJob,
  variant: CompressionVariant,
  event: WorkerCompressResponse
): CompressionVariant {
  if (variant.id !== event.variantId) {
    return variant;
  }

  if (event.kind === "progress") {
    return {
      ...variant,
      progress: Math.max(variant.progress, event.progress),
    };
  }

  if (!event.ok) {
    return {
      ...variant,
      error: event.error,
      progress: 100,
      status: "error",
    };
  }

  const sizeDelta = event.output.size - job.file.size;

  return {
    ...variant,
    autoGenerated: event.autoGenerated,
    format: event.format,
    output: event.output,
    outputName: event.outputName,
    progress: 100,
    sourceFormat: event.sourceFormat,
    strategy: event.strategy,
    sizeDelta,
    status: sizeDelta > 0 ? "larger-than-original" : "done",
  };
}

function applyWorkerEventToJob(
  job: CompressionJob,
  event: WorkerCompressResponse
): CompressionJob {
  if (job.id !== event.sourceId) {
    return job;
  }

  const variants = job.variants.map((variant) =>
    updateVariantFromWorker(job, variant, event)
  );
  const finishedVariant = variants.find(
    (variant) => variant.id === event.variantId
  );
  const nextBestVariantId = getBestVariantId(variants);
  const activeVariantId =
    finishedVariant?.status === "error"
      ? job.activeVariantId
      : nextBestVariantId;

  return {
    ...job,
    activeVariantId,
    bestVariantId: nextBestVariantId,
    error:
      finishedVariant?.status === "error" ? finishedVariant.error : undefined,
    status: getJobStatus(variants),
    variants,
  };
}

function getVariantById(
  job: CompressionJob | undefined,
  variantId: string | null
) {
  if (!(job && variantId)) {
    return null;
  }

  return job.variants.find((variant) => variant.id === variantId) ?? null;
}

function getDownloadTarget(job: CompressionJob | undefined) {
  if (!job) {
    return null;
  }

  const activeVariant = getVariantById(job, job.activeVariantId);
  if (activeVariant?.output && activeVariant.outputName) {
    return { blob: activeVariant.output, name: activeVariant.outputName };
  }

  const bestVariant = getVariantById(job, job.bestVariantId);
  if (bestVariant?.output && bestVariant.outputName) {
    return { blob: bestVariant.output, name: bestVariant.outputName };
  }

  return { blob: job.file, name: job.file.name };
}

export default function CompressorApp() {
  const [settings, setSettings] = useState<CompressionSettings>(
    () => loadSettings() ?? defaultSettings
  );
  const [activePresetId, setActivePresetId] = useState<string | null>(null);
  const [jobs, setJobs] = useState<CompressionJob[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [globalError, setGlobalError] = useState("");
  const addFilesInputRef = useRef<HTMLInputElement>(null);
  const jobsRef = useRef<CompressionJob[]>([]);
  const workerRef = useRef<Worker | null>(null);
  const settingsRef = useRef(settings);

  useEffect(() => {
    settingsRef.current = settings;
  }, [settings]);

  useEffect(() => {
    jobsRef.current = jobs;
  }, [jobs]);

  const selectedJob = useMemo(
    () => jobs.find((job) => job.id === selectedId),
    [jobs, selectedId]
  );
  const selectedSourceFormat = useMemo(
    () => (selectedJob ? formatFromFile(selectedJob.file) : null),
    [selectedJob]
  );
  const fallbackSourceFormat = useMemo(
    () => (jobs[0] ? formatFromFile(jobs[0].file) : null),
    [jobs]
  );
  const hasJobs = jobs.length > 0;
  const hasCompleted = jobs.some((job) => job.status === "done");
  const isProcessing = jobs.some((job) => job.status === "processing");

  useEffect(() => {
    return () => {
      workerRef.current?.terminate();
      workerRef.current = null;
    };
  }, []);

  const ensureWorker = useCallback(() => {
    if (!workerRef.current) {
      workerRef.current = new Worker(
        new URL("../../lib/workers/compression.worker.ts", import.meta.url),
        { type: "module" }
      );
      workerRef.current.onmessage = (
        event: MessageEvent<WorkerCompressResponse>
      ) => {
        setJobs((current) =>
          current.map((job) => applyWorkerEventToJob(job, event.data))
        );
      };
      workerRef.current.onerror = () => {
        setGlobalError(
          "The compression worker stopped before it could finish."
        );
        setJobs((current) =>
          current.map((job) => ({
            ...job,
            error: "The compression worker stopped before it could finish.",
            status: job.status === "processing" ? "error" : job.status,
            variants: job.variants.map((variant) =>
              variant.status === "processing"
                ? {
                    ...variant,
                    error:
                      "The compression worker stopped before it could finish.",
                    progress: 100,
                    status: "error" as const,
                  }
                : variant
            ),
          }))
        );
      };
    }
    return workerRef.current;
  }, []);

  function queueCompression(
    sourceId: string,
    nextSettings: CompressionSettings,
    presetId: string | null,
    autoGenerated: boolean
  ) {
    const job = jobsRef.current.find((entry) => entry.id === sourceId);
    if (!job) {
      return;
    }

    const worker = ensureWorker();
    const sourceFormat = formatFromFile(job.file);
    const tasks = buildCompressionTasks(
      job.file,
      nextSettings,
      presetId,
      autoGenerated
    );
    const nextVariants = tasks.map((task) => {
      const existingVariant = job.variants.find(
        (variant) =>
          variant.signature ===
          settingsSignature(task.settings, task.presetId, task.strategy)
      );

      return createPendingVariant(
        job.file,
        task,
        sourceFormat,
        existingVariant?.id
      );
    });

    setJobs((current) =>
      current.map((entry) => {
        if (entry.id !== sourceId) {
          return entry;
        }

        const variants = [
          ...entry.variants.filter(
            (variant) =>
              !nextVariants.some((nextVariant) => nextVariant.id === variant.id)
          ),
          ...nextVariants,
        ].sort((left, right) => left.createdAt - right.createdAt);

        return {
          ...entry,
          activeVariantId: entry.bestVariantId,
          error: undefined,
          status: "processing",
          variants,
        };
      })
    );

    for (const [index, task] of tasks.entries()) {
      const nextVariant = nextVariants[index];
      if (!nextVariant) {
        continue;
      }

      worker.postMessage({
        autoGenerated: task.autoGenerated,
        file: job.file,
        presetId: task.presetId,
        settings: task.settings,
        sourceFormat,
        sourceId,
        strategy: task.strategy,
        variantId: nextVariant.id,
      });
    }
  }

  const addFiles = useCallback(
    (files: File[]) => {
      const selectedFiles = files.filter((file) =>
        file.type.startsWith("image/")
      );

      if (!selectedFiles.length) {
        setGlobalError(
          "Pick image files and PixelPress will take it from there."
        );
        return;
      }

      const currentSettings = settingsRef.current;
      saveSettings(currentSettings);
      setGlobalError("");
      const worker = ensureWorker();

      const nextJobs: CompressionJob[] = selectedFiles.map((file) => {
        const jobId = crypto.randomUUID();
        const sourceFormat = formatFromFile(file);
        const tasks = buildCompressionTasks(file, currentSettings, null, true);
        const variants = tasks.map((task) =>
          createPendingVariant(file, task, sourceFormat)
        );

        for (const [index, task] of tasks.entries()) {
          const variant = variants[index];
          if (!variant) {
            continue;
          }

          worker.postMessage({
            autoGenerated: task.autoGenerated,
            file,
            presetId: task.presetId,
            settings: task.settings,
            sourceFormat,
            sourceId: jobId,
            strategy: task.strategy,
            variantId: variant.id,
          });
        }

        return {
          activeVariantId: null,
          bestVariantId: null,
          file,
          id: jobId,
          status: "processing",
          variants,
        };
      });

      const combined = [...jobsRef.current, ...nextJobs];
      setJobs(combined);
      setSelectedId((existing) => existing ?? combined[0]?.id ?? null);
    },
    [ensureWorker]
  );

  const fileInput = (
    <input
      accept="image/*"
      className="hidden"
      multiple
      onChange={(event) => {
        addFiles(Array.from(event.target.files ?? []));
        event.currentTarget.value = "";
      }}
      ref={addFilesInputRef}
      type="file"
    />
  );

  function handleSettingsChange(nextSettings: CompressionSettings) {
    setActivePresetId(null);
    setSettings(nextSettings);
    saveSettings(nextSettings);
  }

  function handleApplySettings(nextSettings: CompressionSettings) {
    handleSettingsChange(nextSettings);
    if (selectedJob) {
      queueCompression(selectedJob.id, nextSettings, null, false);
    }
  }

  function handleApplyPreset(presetId: string) {
    if (!selectedJob) {
      return;
    }

    const presetSettings =
      presets.find((entry) => entry.id === presetId)?.settings ??
      defaultSettings;
    setActivePresetId(presetId);
    setSettings(presetSettings);
    saveSettings(presetSettings);
    queueCompression(selectedJob.id, presetSettings, presetId, true);
  }

  function clearQueue() {
    if (isProcessing) {
      return;
    }
    setJobs([]);
    setSelectedId(null);
    setGlobalError("");
  }

  function openAddFilesPicker() {
    addFilesInputRef.current?.click();
  }

  function downloadSelected() {
    const target = getDownloadTarget(selectedJob);
    if (target) {
      downloadBlob(target.blob, target.name);
    }
  }

  async function downloadAllZip() {
    if (!jobs.length) {
      return;
    }

    try {
      const archive: Record<string, Uint8Array> = {
        "README.txt": strToU8(
          "Generated by PixelPress. Smaller versions are included when they genuinely saved space. Otherwise the original file was kept."
        ),
      };
      const usedNames = new Set<string>(Object.keys(archive));

      for (const job of jobs) {
        const target = getDownloadTarget(job);
        if (!target) {
          continue;
        }

        const safeName = uniqueName(target.name, usedNames);
        archive[safeName] = new Uint8Array(await target.blob.arrayBuffer());
      }

      const zipData = await new Promise<Uint8Array>((resolve, reject) => {
        zip(archive, { level: 6 }, (err, data) => {
          if (err) {
            reject(err);
            return;
          }
          resolve(data);
        });
      });
      const zipBuffer = Uint8Array.from(zipData).buffer;

      downloadBlob(
        new Blob([zipBuffer], { type: "application/zip" }),
        "pixelpress-best-results.zip"
      );
    } catch (err) {
      setGlobalError(
        err instanceof Error ? err.message : "Could not put the zip together."
      );
    }
  }

  function setActiveVariant(sourceId: string, variantId: string | null) {
    setJobs((current) =>
      current.map((job) =>
        job.id === sourceId ? { ...job, activeVariantId: variantId } : job
      )
    );
  }

  if (!hasJobs) {
    return (
      <div className="flex h-[calc(100dvh-3.5rem)] flex-col overflow-hidden">
        <div className="flex flex-1 flex-col">
          <Dropzone onFiles={addFiles} />
        </div>
        {fileInput}
        {globalError && (
          <p className="border-[color:color-mix(in_oklab,var(--color-error)_30%,transparent)] border-t bg-[color:color-mix(in_oklab,var(--color-error)_12%,transparent)] px-4 py-2.5 text-center text-[0.88rem] text-[color:color-mix(in_oklab,var(--color-error)_72%,white_28%)]">
            {globalError}
          </p>
        )}
        <ToolbarControls
          activePresetId={activePresetId}
          hasCompleted={hasCompleted}
          hasJobs={hasJobs}
          hasSelection={!!selectedJob}
          isProcessing={isProcessing}
          onApplyPreset={handleApplyPreset}
          onApplySettings={handleApplySettings}
          onChange={handleSettingsChange}
          onClear={clearQueue}
          onDownloadSelected={downloadSelected}
          onDownloadZip={downloadAllZip}
          settings={settings}
          sourceFormat={selectedSourceFormat ?? fallbackSourceFormat}
        />
      </div>
    );
  }

  return (
    <div className="flex h-[calc(100dvh-3.5rem)] flex-col overflow-hidden">
      <div className="flex items-center justify-between border-border border-b px-3 py-2">
        <p className="text-[0.82rem] text-white/55">
          PixelPress keeps the smallest result by default. Change the format
          only when you want a different export.
        </p>
        <button
          className="inline-flex items-center gap-1.5 whitespace-nowrap rounded-[0.55rem] border border-border bg-white/4 px-3 py-1.5 font-medium text-[0.82rem] text-muted-strong hover:border-border-strong hover:bg-white/8"
          onClick={openAddFilesPicker}
          type="button"
        >
          <span className="text-[0.92rem] leading-none">+</span>
          Add files
        </button>
        {fileInput}
      </div>

      <div className="flex min-h-0 flex-1 flex-col overflow-hidden md:flex-row">
        <CompressionList
          jobs={jobs}
          onSelect={setSelectedId}
          selectedId={selectedId}
        />
        <div className="flex min-w-0 flex-1 flex-col overflow-hidden">
          <PreviewPanel
            job={selectedJob}
            onSelectVariant={(variantId) => {
              if (selectedJob) {
                setActiveVariant(selectedJob.id, variantId);
              }
            }}
          />
        </div>
      </div>

      {globalError && (
        <p className="border-[color:color-mix(in_oklab,var(--color-error)_30%,transparent)] border-t bg-[color:color-mix(in_oklab,var(--color-error)_12%,transparent)] px-4 py-2.5 text-center text-[0.88rem] text-[color:color-mix(in_oklab,var(--color-error)_72%,white_28%)]">
          {globalError}
        </p>
      )}

      <ToolbarControls
        activePresetId={activePresetId}
        hasCompleted={hasCompleted}
        hasJobs={hasJobs}
        hasSelection={!!selectedJob}
        isProcessing={isProcessing}
        onApplyPreset={handleApplyPreset}
        onApplySettings={handleApplySettings}
        onChange={handleSettingsChange}
        onClear={clearQueue}
        onDownloadSelected={downloadSelected}
        onDownloadZip={downloadAllZip}
        settings={settings}
        sourceFormat={selectedSourceFormat ?? fallbackSourceFormat}
      />
    </div>
  );
}
